name: release1

# 触发工作流程的事件
on:
  push:
    branches:
      - release
# 按顺序运行作业
jobs:
  publish-gpr:
    # 指定的运行器环境
    runs-on: ubuntu-latest
    # 设置 node 版本
    strategy:
      matrix:
        node-version: [16]
        pnpm-version: [8]
    steps:
      # 拉取 github 仓库代码
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.pnpm-version }}
      # 设定 node 环境
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          # 设置发包 npm 地址仓库
          registry-url: https://registry.npmjs.org
          cache: 'pnpm'
      # 安装依赖，相当于 npm ci
      - name: Install dependencies
        run: pnpm install
      # 执行构建步骤
      - name: 构建
        run: |
          cd ./packages/components
          pnpm run build
          cd ../../
          echo $(pwd)       
      # 执行部署

      - name: 发布
        run: |
          echo $(pwd)
          father_file="/home/runner/work/pink-flower-ui"
          for dir in $(ls /home/runner/work/pink-flower-ui/pink-flower-ui/packages)
          do
            [ -d $dir ] && echo $dir
          done
          pnpm changeset publish
        env:
          # 设置的 NPM_TOKEN
          NODE_AUTH_TOKEN: ${{secrets.NPM_ACCESS_TOKEN}}